### ISSUE TITLE
Accounts Keys are insecure

### ISSUE THREAD

**Issue by schenkty** [besoeasy/nano-payment#3]
Account keys such as seeds and private keys should never be passed within an http request as they are extremely exposed during transmission. This method would make potential sense in a situation where the http transmission is on a segmented and secure private network. Unfortunately this project is targeted at operating on insecure public hosting solutions such as Heroku which results in the project not being sufficiently secure for financial transactions.

**Comment by besoeasy** [comment]
i know that please check the Readme.md before opening a issue

b90aad3 10 days ago

https://github.com/besoeasy/nano-payment/blob/b90aad341293d6ecadcc93869acd02c8752c6f15/README.md
