### ISSUE TITLE
Should not depend on third party solutions

### ISSUE THREAD

**Issue by schenkty** [besoeasy/nano-payment#4]
Currently transaction processing is piggybacking on the third party solution, NanoVault. This method runs directly against the benefits of cryptocurrency decentralization as you are forcing yourself to trust a single third party for your "source of truth". Additionally the reliability of this project is also in the hands of NanoVault which has been increasingly known to be unreliable. Lastly all information has to be transmitted to NanoVault's API which in turn is sent to NanoVault's node before working back to the API and then back to this node.js service. This transmission path adds extraordinary amounts of latency to all transaction functions which forces this service to grind to a halt under load. 

I strongly believe this should be fixed to communicate directly with a Nano Node only.

**Comment by Falsen** [comment]
He mentioned that it's for "day to day projects" so I think setting up a nano-node for just simple and fun projects is a big hastle. Better if we have an open ecosystem that is as easy as possible to use so that we get more devs involved

**Comment by besoeasy** [comment]
> you can easily change to your local node, from script  !  

this is just added for users who are deploying to **heroku** or **repl.it**, could test the script, dedicated node is recommended if you process transactions whole day.
